export const businessInfo = {
  name: "SagO Mobile & Computer Accessories",
  shortName: "SagO",
  tagline: "Your One-Stop Shop for Mobile & Computer Accessories",
  description:
    "Buy mobile and computer accessories in Tirunelveli and get mobile service, laptop and desktop service support, recharges, SIM cards, feature phones, Xerox, and printout services.",
  category: [
    "Cell Phone Accessory Store",
    "Computer Accessories Store",
    "Mobile Phone Repair Shop",
    "Computer Repair Service",
    "Print Shop",
  ],
  address: {
    street: "No. 9, EB Society Complex, Sivanthipatti Main Road",
    landmark: "Near Anbunagar Railway Gate",
    area: "Maharaja Nagar",
    city: "Tirunelveli",
    state: "Tamil Nadu",
    zip: "627011",
    country: "India",
    full: "No. 9, EB Society Complex, Sivanthipatti Main Road, Near Anbunagar Railway Gate, Maharaja Nagar, Tirunelveli, Tamil Nadu 627011, India",
  },
  phone: "+918438887716",
  phoneDisplay: "+91 84388 87716",
  whatsapp: "https://wa.me/918438887716",
  email: "info@sagoaccessories.com",
  googleMapsEmbed:
    "https://www.google.com/maps?q=8.7050806,77.7501435&z=17&output=embed",
  googleMapsLink:
    "https://www.google.com/maps/place/SagO+Mobile+%26+Computer+Accessories/@8.6929467,77.7420463,15.18z/data=!4m6!3m5!1s0x3b040dbdab2b9c5b:0x42e41d20aa09d211!8m2!3d8.7050806!4d77.7501435!16s%2Fg%2F11r8xg5qf7",
  googleReviewLink: "https://www.google.com/maps/place/SagO+Mobile+%26+Computer+Accessories/@8.6929467,77.7420463,15.18z/data=!4m6!3m5!1s0x3b040dbdab2b9c5b:0x42e41d20aa09d211!8m2!3d8.7050806!4d77.7501435!16s%2Fg%2F11r8xg5qf7?authuser=0&hl=en&entry=ttu&g_ep=EgoyMDI2MDUyMC4wIKXMDSoASAFQAw%3D%3D",
  formspreeEndpoint: "https://formspree.io/f/YOUR_FORM_ID",
  socialMedia: {
    instagram: "https://www.instagram.com/sagomobiles?igsh=cHF2cTd5bXRxbXB0",
    facebook: "https://www.facebook.com/share/18RNoUn2HH/",
  },
  hours: [
    { day: "Monday", open: "9:15 AM - 2:00 PM, 4:00 PM", close: "9:15 PM", isClosed: false },
    { day: "Tuesday", open: "9:15 AM - 2:00 PM, 4:00 PM", close: "9:15 PM", isClosed: false },
    { day: "Wednesday", open: "9:15 AM - 2:00 PM, 4:00 PM", close: "9:15 PM", isClosed: false },
    { day: "Thursday", open: "9:15 AM - 2:00 PM, 4:00 PM", close: "9:15 PM", isClosed: false },
    { day: "Friday", open: "9:15 AM - 2:00 PM, 4:00 PM", close: "9:15 PM", isClosed: false },
    { day: "Saturday", open: "9:15 AM - 2:00 PM, 4:00 PM", close: "9:15 PM", isClosed: false },
    { day: "Sunday", open: "", close: "", isClosed: true },
  ],
  serviceArea: "Maharaja Nagar, Sivanthipatti Main Road, and nearby Tirunelveli areas",
  nearbyAreas: [
    "Maharaja Nagar",
    "Thiyagaraja Nagar",
    "Sivanthipatti",
    "Anbu Nagar",
    "EB Colony",
    "Pothigai Nagar",
    "Ponvila Nagar",
    "Railway Feeder Road",
    "TVS Nagar",
    "Tamirapathi Colony",
    "LIC Colony",
    "Anaiyarkulam",
    "Canara Bank Colony",
    "Perumalpuram",
    "IOB Colony",
    "Velavar Colony",
    "Kuthukkal",
    "Rajagopalapuram",
    "Mallika Colony",
    "Kumaresan Nagar",
    "Muthoor",
    "Kodikulam",
    "Porunai Museum",
    "Ramachandra Nagar",
  ],
  seo: {
    title:
      "Mobile Accessories, Service, Xerox & Printout in Tirunelveli | SagO",
    description:
      "SagO Mobile & Computer Accessories in Maharaja Nagar, Tirunelveli offers mobile accessories, computer accessories, mobile service, laptop and desktop service support, recharges, SIM cards, feature phones, Xerox, and printout services near Thiyagaraja Nagar, Sivanthipatti, Anbu Nagar, and EB Colony.",
    keywords: [
      "best mobile accessories shop in Tirunelveli",
      "computer accessories store Tirunelveli",
      "mobile accessories Maharaja Nagar",
      "computer accessories Maharaja Nagar",
      "mobile repair shop Maharaja Nagar",
      "laptop service Maharaja Nagar",
      "Xerox shop Maharaja Nagar",
      "printout shop Maharaja Nagar",
      "mobile shop Thiyagaraja Nagar",
      "mobile service Thiyagaraja Nagar",
      "phone cover shop Thiyagaraja Nagar",
      "tempered glass shop Thiyagaraja Nagar",
      "mobile service Sivanthipatti",
      "laptop service Sivanthipatti",
      "mobile repair near Sivanthipatti Main Road",
      "computer accessories near Sivanthipatti Main Road",
      "mobile accessories Anbu Nagar",
      "Xerox printout Anbu Nagar",
      "mobile recharge Anbu Nagar",
      "mobile recharge EB Colony",
      "SIM card sales EB Colony",
      "printout shop EB Colony",
      "mobile accessories Pothigai Nagar",
      "mobile service Pothigai Nagar",
      "mobile shop Ponvila Nagar",
      "mobile recharge Ponvila Nagar",
      "computer accessories Railway Feeder Road",
      "Xerox shop Railway Feeder Road",
      "mobile service TVS Nagar",
      "phone accessories TVS Nagar",
      "laptop service Tamirapathi Colony",
      "desktop service Tamirapathi Colony",
      "Xerox printout LIC Colony",
      "mobile shop LIC Colony",
      "mobile recharge Anaiyarkulam",
      "feature phone shop Anaiyarkulam",
      "SIM card sales Canara Bank Colony",
      "printout shop Canara Bank Colony",
      "mobile accessories Perumalpuram",
      "laptop charger shop Perumalpuram",
      "computer service IOB Colony",
      "mobile recharge IOB Colony",
      "feature phones Velavar Colony",
      "mobile accessories Velavar Colony",
      "mobile service Kuthukkal",
      "mobile accessories Rajagopalapuram",
      "Xerox printout Mallika Colony",
      "laptop service Kumaresan Nagar",
      "mobile recharge Muthoor",
      "SIM card sales Kodikulam",
      "mobile shop near Porunai Museum",
      "computer accessories Ramachandra Nagar",
      "mobile shop near Sivanthipatti Main Road",
      "mobile shop near Anbunagar Railway Gate",
      "accessories shop near Anbunagar Railway Gate",
      "Xerox near Anbunagar Railway Gate",
      "mobile service Tirunelveli",
      "mobile repair shop Tirunelveli",
      "laptop service Tirunelveli",
      "laptop repair Tirunelveli",
      "desktop service Tirunelveli",
      "desktop repair Tirunelveli",
      "mobile recharge Tirunelveli",
      "mobile recharge shop Tirunelveli",
      "SIM card sales Tirunelveli",
      "SIM card shop Tirunelveli",
      "feature phones Tirunelveli",
      "feature phone shop Tirunelveli",
      "Xerox printout Tirunelveli",
      "Xerox shop Tirunelveli",
      "printout shop Tirunelveli",
      "mobile shop near me Tirunelveli",
      "mobile accessories near me Tirunelveli",
      "computer accessories near me Tirunelveli",
      "premium mobile covers Tirunelveli",
      "phone cover shop Tirunelveli",
      "original laptop chargers Tirunelveli",
      "laptop charger shop Tirunelveli",
      "SSD and RAM upgrade Tirunelveli",
      "tempered glass installation Tirunelveli",
      "tempered glass shop Tirunelveli",
      "SagO Mobile and Computer Accessories",
      "computer peripherals Tirunelveli",
    ],
    ogImage: "/og-image.png",
    siteUrl: "https://sagoaccessories.com",
  },
  analytics: {
    googleAnalyticsId: "G-XXXXXXXXXX", // REPLACE_WITH_ACTUAL_GA_ID
    googleSearchConsoleId: "XXXXXXXXXX", // REPLACE_WITH_ACTUAL_GSC_VERIFICATION
  },
} as const;

export type BusinessInfo = typeof businessInfo;
